// router.fbs
// Compile with: flatc --rust router.fbs

enum DeviceState: byte { Allowed = 0, Blocked = 1, Suspicious = 2 }

table RegisterRequest {
    network_id: string;
    mac: string;
    hostname: string;
    ip: string;
    manufacturer: string;
}

table ChangeStateRequest {
    network_id: string;
    mac: string;
    state: string;
}

table TelemetryReport {
    network_id: string;
    mac: string;
    bytes_in: ulong;
    bytes_out: ulong;
    unique_internal_ips: uint;       
    unique_external_ips: uint;
    total_connections: uint;         
    passed_connections: uint;
    dropped_connections: uint;
    anomaly_flags_count: uint;
    heuristic_flags_count: uint;
    infra_alert_count: uint;
    port_entropy_score: float;
}

union IncomingPayload {
    RegisterRequest,
    ChangeStateRequest,
    TelemetryReport
}

table RouterMessage {
    payload: IncomingPayload;
}

table ThreatIntelPayload {
ad_domains: [string];
banned_ips: [string];
}

table RouterResponse {
status: string;
mac: string;
threat_intel: ThreatIntelPayload;
}

root_type RouterMessage;