---
- name: SOHO NDR - Active Response Action
  hosts: localhost
  become: yes
  vars:
    attacker_ip: "{{ src_ip }}"

  tasks:
    - name: Block the malicious IP using iptables
      ansible.builtin.iptables:
        chain: INPUT
        source: "{{ attacker_ip }}"
        jump: DROP
        comment: "Blocked by Ranim's Automation Playbook"

    - name: Print block confirmation to console
      ansible.builtin.debug:
        msg: "ALERT: Successfully blocked malicious IP -> {{ attacker_ip }}"