// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_DEVICE_STATE: i8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_DEVICE_STATE: i8 = 2;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_DEVICE_STATE: [DeviceState; 3] = [
  DeviceState::Allowed,
  DeviceState::Blocked,
  DeviceState::Suspicious,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct DeviceState(pub i8);
#[allow(non_upper_case_globals)]
impl DeviceState {
  pub const Allowed: Self = Self(0);
  pub const Blocked: Self = Self(1);
  pub const Suspicious: Self = Self(2);

  pub const ENUM_MIN: i8 = 0;
  pub const ENUM_MAX: i8 = 2;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::Allowed,
    Self::Blocked,
    Self::Suspicious,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::Allowed => Some("Allowed"),
      Self::Blocked => Some("Blocked"),
      Self::Suspicious => Some("Suspicious"),
      _ => None,
    }
  }
}
impl core::fmt::Debug for DeviceState {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> flatbuffers::Follow<'a> for DeviceState {
  type Inner = Self;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe {
      flatbuffers::read_scalar_at::<i8>(buf, loc)
    };
    Self(b)
  }
}

impl flatbuffers::Push for DeviceState {
    type Output = DeviceState;
    #[inline]
    fn push(&self, dst: &mut [u8], _rest: &[u8]) {
        unsafe { flatbuffers::emplace_scalar::<i8>(dst, self.0); }
    }
}

impl flatbuffers::EndianScalar for DeviceState {
  #[inline]
  fn to_little_endian(self) -> Self {
    let b = i8::to_le(self.0);
    Self(b)
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(self) -> Self {
    let b = i8::from_le(self.0);
    Self(b)
  }
}

impl<'a> flatbuffers::Verifiable for DeviceState {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    i8::run_verifier(v, pos)
  }
}

impl flatbuffers::SimpleToVerifyInSlice for DeviceState {}
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_INCOMING_PAYLOAD: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_INCOMING_PAYLOAD: u8 = 3;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_INCOMING_PAYLOAD: [IncomingPayload; 4] = [
  IncomingPayload::NONE,
  IncomingPayload::RegisterRequest,
  IncomingPayload::ChangeStateRequest,
  IncomingPayload::TelemetryReport,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct IncomingPayload(pub u8);
#[allow(non_upper_case_globals)]
impl IncomingPayload {
  pub const NONE: Self = Self(0);
  pub const RegisterRequest: Self = Self(1);
  pub const ChangeStateRequest: Self = Self(2);
  pub const TelemetryReport: Self = Self(3);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 3;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::NONE,
    Self::RegisterRequest,
    Self::ChangeStateRequest,
    Self::TelemetryReport,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::NONE => Some("NONE"),
      Self::RegisterRequest => Some("RegisterRequest"),
      Self::ChangeStateRequest => Some("ChangeStateRequest"),
      Self::TelemetryReport => Some("TelemetryReport"),
      _ => None,
    }
  }
}
impl core::fmt::Debug for IncomingPayload {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> flatbuffers::Follow<'a> for IncomingPayload {
  type Inner = Self;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe {
      flatbuffers::read_scalar_at::<u8>(buf, loc)
    };
    Self(b)
  }
}

impl flatbuffers::Push for IncomingPayload {
    type Output = IncomingPayload;
    #[inline]
    fn push(&self, dst: &mut [u8], _rest: &[u8]) {
        unsafe { flatbuffers::emplace_scalar::<u8>(dst, self.0); }
    }
}

impl flatbuffers::EndianScalar for IncomingPayload {
  #[inline]
  fn to_little_endian(self) -> Self {
    let b = u8::to_le(self.0);
    Self(b)
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(self) -> Self {
    let b = u8::from_le(self.0);
    Self(b)
  }
}

impl<'a> flatbuffers::Verifiable for IncomingPayload {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    u8::run_verifier(v, pos)
  }
}

impl flatbuffers::SimpleToVerifyInSlice for IncomingPayload {}
pub struct IncomingPayloadUnionTableOffset {}

pub enum RegisterRequestOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct RegisterRequest<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for RegisterRequest<'a> {
  type Inner = RegisterRequest<'a>;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table { buf, loc } }
  }
}

impl<'a> RegisterRequest<'a> {
  pub const VT_NETWORK_ID: flatbuffers::VOffsetT = 4;
  pub const VT_MAC: flatbuffers::VOffsetT = 6;
  pub const VT_HOSTNAME: flatbuffers::VOffsetT = 8;
  pub const VT_IP: flatbuffers::VOffsetT = 10;
  pub const VT_MANUFACTURER: flatbuffers::VOffsetT = 12;

  #[inline]
  pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    RegisterRequest { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args RegisterRequestArgs<'args>
  ) -> flatbuffers::WIPOffset<RegisterRequest<'bldr>> {
    let mut builder = RegisterRequestBuilder::new(_fbb);
    if let Some(x) = args.manufacturer { builder.add_manufacturer(x); }
    if let Some(x) = args.ip { builder.add_ip(x); }
    if let Some(x) = args.hostname { builder.add_hostname(x); }
    if let Some(x) = args.mac { builder.add_mac(x); }
    if let Some(x) = args.network_id { builder.add_network_id(x); }
    builder.finish()
  }


  #[inline]
  pub fn network_id(&self) -> Option<&'a str> {
    self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(RegisterRequest::VT_NETWORK_ID, None)
  }
  #[inline]
  pub fn mac(&self) -> Option<&'a str> {
    self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(RegisterRequest::VT_MAC, None)
  }
  #[inline]
  pub fn hostname(&self) -> Option<&'a str> {
    self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(RegisterRequest::VT_HOSTNAME, None)
  }
  #[inline]
  pub fn ip(&self) -> Option<&'a str> {
    self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(RegisterRequest::VT_IP, None)
  }
  #[inline]
  pub fn manufacturer(&self) -> Option<&'a str> {
    self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(RegisterRequest::VT_MANUFACTURER, None)
  }
}

impl flatbuffers::Verifiable for RegisterRequest<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("network_id", Self::VT_NETWORK_ID, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("mac", Self::VT_MAC, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("hostname", Self::VT_HOSTNAME, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("ip", Self::VT_IP, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("manufacturer", Self::VT_MANUFACTURER, false)?
     .finish();
    Ok(())
  }
}
pub struct RegisterRequestArgs<'a> {
    pub network_id: Option<flatbuffers::WIPOffset<&'a str>>,
    pub mac: Option<flatbuffers::WIPOffset<&'a str>>,
    pub hostname: Option<flatbuffers::WIPOffset<&'a str>>,
    pub ip: Option<flatbuffers::WIPOffset<&'a str>>,
    pub manufacturer: Option<flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for RegisterRequestArgs<'a> {
  #[inline]
  fn default() -> Self {
    RegisterRequestArgs {
      network_id: None,
      mac: None,
      hostname: None,
      ip: None,
      manufacturer: None,
    }
  }
}

pub struct RegisterRequestBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> RegisterRequestBuilder<'a, 'b> {
  #[inline]
  pub fn add_network_id(&mut self, network_id: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(RegisterRequest::VT_NETWORK_ID, network_id);
  }
  #[inline]
  pub fn add_mac(&mut self, mac: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(RegisterRequest::VT_MAC, mac);
  }
  #[inline]
  pub fn add_hostname(&mut self, hostname: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(RegisterRequest::VT_HOSTNAME, hostname);
  }
  #[inline]
  pub fn add_ip(&mut self, ip: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(RegisterRequest::VT_IP, ip);
  }
  #[inline]
  pub fn add_manufacturer(&mut self, manufacturer: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(RegisterRequest::VT_MANUFACTURER, manufacturer);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> RegisterRequestBuilder<'a, 'b> {
    let start = _fbb.start_table();
    RegisterRequestBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<RegisterRequest<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for RegisterRequest<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("RegisterRequest");
      ds.field("network_id", &self.network_id());
      ds.field("mac", &self.mac());
      ds.field("hostname", &self.hostname());
      ds.field("ip", &self.ip());
      ds.field("manufacturer", &self.manufacturer());
      ds.finish()
  }
}
pub enum ChangeStateRequestOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ChangeStateRequest<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for ChangeStateRequest<'a> {
  type Inner = ChangeStateRequest<'a>;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table { buf, loc } }
  }
}

impl<'a> ChangeStateRequest<'a> {
  pub const VT_NETWORK_ID: flatbuffers::VOffsetT = 4;
  pub const VT_MAC: flatbuffers::VOffsetT = 6;
  pub const VT_STATE: flatbuffers::VOffsetT = 8;

  #[inline]
  pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    ChangeStateRequest { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args ChangeStateRequestArgs<'args>
  ) -> flatbuffers::WIPOffset<ChangeStateRequest<'bldr>> {
    let mut builder = ChangeStateRequestBuilder::new(_fbb);
    if let Some(x) = args.state { builder.add_state(x); }
    if let Some(x) = args.mac { builder.add_mac(x); }
    if let Some(x) = args.network_id { builder.add_network_id(x); }
    builder.finish()
  }


  #[inline]
  pub fn network_id(&self) -> Option<&'a str> {
    self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(ChangeStateRequest::VT_NETWORK_ID, None)
  }
  #[inline]
  pub fn mac(&self) -> Option<&'a str> {
    self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(ChangeStateRequest::VT_MAC, None)
  }
  #[inline]
  pub fn state(&self) -> Option<&'a str> {
    self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(ChangeStateRequest::VT_STATE, None)
  }
}

impl flatbuffers::Verifiable for ChangeStateRequest<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("network_id", Self::VT_NETWORK_ID, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("mac", Self::VT_MAC, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("state", Self::VT_STATE, false)?
     .finish();
    Ok(())
  }
}
pub struct ChangeStateRequestArgs<'a> {
    pub network_id: Option<flatbuffers::WIPOffset<&'a str>>,
    pub mac: Option<flatbuffers::WIPOffset<&'a str>>,
    pub state: Option<flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for ChangeStateRequestArgs<'a> {
  #[inline]
  fn default() -> Self {
    ChangeStateRequestArgs {
      network_id: None,
      mac: None,
      state: None,
    }
  }
}

pub struct ChangeStateRequestBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> ChangeStateRequestBuilder<'a, 'b> {
  #[inline]
  pub fn add_network_id(&mut self, network_id: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(ChangeStateRequest::VT_NETWORK_ID, network_id);
  }
  #[inline]
  pub fn add_mac(&mut self, mac: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(ChangeStateRequest::VT_MAC, mac);
  }
  #[inline]
  pub fn add_state(&mut self, state: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(ChangeStateRequest::VT_STATE, state);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> ChangeStateRequestBuilder<'a, 'b> {
    let start = _fbb.start_table();
    ChangeStateRequestBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<ChangeStateRequest<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for ChangeStateRequest<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("ChangeStateRequest");
      ds.field("network_id", &self.network_id());
      ds.field("mac", &self.mac());
      ds.field("state", &self.state());
      ds.finish()
  }
}
pub enum TelemetryReportOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct TelemetryReport<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for TelemetryReport<'a> {
  type Inner = TelemetryReport<'a>;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table { buf, loc } }
  }
}

impl<'a> TelemetryReport<'a> {
  pub const VT_NETWORK_ID: flatbuffers::VOffsetT = 4;
  pub const VT_MAC: flatbuffers::VOffsetT = 6;
  pub const VT_BYTES_IN: flatbuffers::VOffsetT = 8;
  pub const VT_BYTES_OUT: flatbuffers::VOffsetT = 10;
  pub const VT_UNIQUE_INTERNAL_IPS: flatbuffers::VOffsetT = 12;
  pub const VT_UNIQUE_EXTERNAL_IPS: flatbuffers::VOffsetT = 14;
  pub const VT_TOTAL_CONNECTIONS: flatbuffers::VOffsetT = 16;
  pub const VT_PASSED_CONNECTIONS: flatbuffers::VOffsetT = 18;
  pub const VT_DROPPED_CONNECTIONS: flatbuffers::VOffsetT = 20;
  pub const VT_ANOMALY_FLAGS_COUNT: flatbuffers::VOffsetT = 22;
  pub const VT_HEURISTIC_FLAGS_COUNT: flatbuffers::VOffsetT = 24;
  pub const VT_INFRA_ALERT_COUNT: flatbuffers::VOffsetT = 26;
  pub const VT_PORT_ENTROPY_SCORE: flatbuffers::VOffsetT = 28;

  #[inline]
  pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    TelemetryReport { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args TelemetryReportArgs<'args>
  ) -> flatbuffers::WIPOffset<TelemetryReport<'bldr>> {
    let mut builder = TelemetryReportBuilder::new(_fbb);
    builder.add_bytes_out(args.bytes_out);
    builder.add_bytes_in(args.bytes_in);
    builder.add_port_entropy_score(args.port_entropy_score);
    builder.add_infra_alert_count(args.infra_alert_count);
    builder.add_heuristic_flags_count(args.heuristic_flags_count);
    builder.add_anomaly_flags_count(args.anomaly_flags_count);
    builder.add_dropped_connections(args.dropped_connections);
    builder.add_passed_connections(args.passed_connections);
    builder.add_total_connections(args.total_connections);
    builder.add_unique_external_ips(args.unique_external_ips);
    builder.add_unique_internal_ips(args.unique_internal_ips);
    if let Some(x) = args.mac { builder.add_mac(x); }
    if let Some(x) = args.network_id { builder.add_network_id(x); }
    builder.finish()
  }


  #[inline]
  pub fn network_id(&self) -> Option<&'a str> {
    self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(TelemetryReport::VT_NETWORK_ID, None)
  }
  #[inline]
  pub fn mac(&self) -> Option<&'a str> {
    self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(TelemetryReport::VT_MAC, None)
  }
  #[inline]
  pub fn bytes_in(&self) -> u64 {
    self._tab.get::<u64>(TelemetryReport::VT_BYTES_IN, Some(0)).unwrap()
  }
  #[inline]
  pub fn bytes_out(&self) -> u64 {
    self._tab.get::<u64>(TelemetryReport::VT_BYTES_OUT, Some(0)).unwrap()
  }
  #[inline]
  pub fn unique_internal_ips(&self) -> u32 {
    self._tab.get::<u32>(TelemetryReport::VT_UNIQUE_INTERNAL_IPS, Some(0)).unwrap()
  }
  #[inline]
  pub fn unique_external_ips(&self) -> u32 {
    self._tab.get::<u32>(TelemetryReport::VT_UNIQUE_EXTERNAL_IPS, Some(0)).unwrap()
  }
  #[inline]
  pub fn total_connections(&self) -> u32 {
    self._tab.get::<u32>(TelemetryReport::VT_TOTAL_CONNECTIONS, Some(0)).unwrap()
  }
  #[inline]
  pub fn passed_connections(&self) -> u32 {
    self._tab.get::<u32>(TelemetryReport::VT_PASSED_CONNECTIONS, Some(0)).unwrap()
  }
  #[inline]
  pub fn dropped_connections(&self) -> u32 {
    self._tab.get::<u32>(TelemetryReport::VT_DROPPED_CONNECTIONS, Some(0)).unwrap()
  }
  #[inline]
  pub fn anomaly_flags_count(&self) -> u32 {
    self._tab.get::<u32>(TelemetryReport::VT_ANOMALY_FLAGS_COUNT, Some(0)).unwrap()
  }
  #[inline]
  pub fn heuristic_flags_count(&self) -> u32 {
    self._tab.get::<u32>(TelemetryReport::VT_HEURISTIC_FLAGS_COUNT, Some(0)).unwrap()
  }
  #[inline]
  pub fn infra_alert_count(&self) -> u32 {
    self._tab.get::<u32>(TelemetryReport::VT_INFRA_ALERT_COUNT, Some(0)).unwrap()
  }
  #[inline]
  pub fn port_entropy_score(&self) -> f32 {
    self._tab.get::<f32>(TelemetryReport::VT_PORT_ENTROPY_SCORE, Some(0.0)).unwrap()
  }
}

impl flatbuffers::Verifiable for TelemetryReport<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("network_id", Self::VT_NETWORK_ID, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("mac", Self::VT_MAC, false)?
     .visit_field::<u64>("bytes_in", Self::VT_BYTES_IN, false)?
     .visit_field::<u64>("bytes_out", Self::VT_BYTES_OUT, false)?
     .visit_field::<u32>("unique_internal_ips", Self::VT_UNIQUE_INTERNAL_IPS, false)?
     .visit_field::<u32>("unique_external_ips", Self::VT_UNIQUE_EXTERNAL_IPS, false)?
     .visit_field::<u32>("total_connections", Self::VT_TOTAL_CONNECTIONS, false)?
     .visit_field::<u32>("passed_connections", Self::VT_PASSED_CONNECTIONS, false)?
     .visit_field::<u32>("dropped_connections", Self::VT_DROPPED_CONNECTIONS, false)?
     .visit_field::<u32>("anomaly_flags_count", Self::VT_ANOMALY_FLAGS_COUNT, false)?
     .visit_field::<u32>("heuristic_flags_count", Self::VT_HEURISTIC_FLAGS_COUNT, false)?
     .visit_field::<u32>("infra_alert_count", Self::VT_INFRA_ALERT_COUNT, false)?
     .visit_field::<f32>("port_entropy_score", Self::VT_PORT_ENTROPY_SCORE, false)?
     .finish();
    Ok(())
  }
}
pub struct TelemetryReportArgs<'a> {
    pub network_id: Option<flatbuffers::WIPOffset<&'a str>>,
    pub mac: Option<flatbuffers::WIPOffset<&'a str>>,
    pub bytes_in: u64,
    pub bytes_out: u64,
    pub unique_internal_ips: u32,
    pub unique_external_ips: u32,
    pub total_connections: u32,
    pub passed_connections: u32,
    pub dropped_connections: u32,
    pub anomaly_flags_count: u32,
    pub heuristic_flags_count: u32,
    pub infra_alert_count: u32,
    pub port_entropy_score: f32,
}
impl<'a> Default for TelemetryReportArgs<'a> {
  #[inline]
  fn default() -> Self {
    TelemetryReportArgs {
      network_id: None,
      mac: None,
      bytes_in: 0,
      bytes_out: 0,
      unique_internal_ips: 0,
      unique_external_ips: 0,
      total_connections: 0,
      passed_connections: 0,
      dropped_connections: 0,
      anomaly_flags_count: 0,
      heuristic_flags_count: 0,
      infra_alert_count: 0,
      port_entropy_score: 0.0,
    }
  }
}

pub struct TelemetryReportBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> TelemetryReportBuilder<'a, 'b> {
  #[inline]
  pub fn add_network_id(&mut self, network_id: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(TelemetryReport::VT_NETWORK_ID, network_id);
  }
  #[inline]
  pub fn add_mac(&mut self, mac: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(TelemetryReport::VT_MAC, mac);
  }
  #[inline]
  pub fn add_bytes_in(&mut self, bytes_in: u64) {
    self.fbb_.push_slot::<u64>(TelemetryReport::VT_BYTES_IN, bytes_in, 0);
  }
  #[inline]
  pub fn add_bytes_out(&mut self, bytes_out: u64) {
    self.fbb_.push_slot::<u64>(TelemetryReport::VT_BYTES_OUT, bytes_out, 0);
  }
  #[inline]
  pub fn add_unique_internal_ips(&mut self, unique_internal_ips: u32) {
    self.fbb_.push_slot::<u32>(TelemetryReport::VT_UNIQUE_INTERNAL_IPS, unique_internal_ips, 0);
  }
  #[inline]
  pub fn add_unique_external_ips(&mut self, unique_external_ips: u32) {
    self.fbb_.push_slot::<u32>(TelemetryReport::VT_UNIQUE_EXTERNAL_IPS, unique_external_ips, 0);
  }
  #[inline]
  pub fn add_total_connections(&mut self, total_connections: u32) {
    self.fbb_.push_slot::<u32>(TelemetryReport::VT_TOTAL_CONNECTIONS, total_connections, 0);
  }
  #[inline]
  pub fn add_passed_connections(&mut self, passed_connections: u32) {
    self.fbb_.push_slot::<u32>(TelemetryReport::VT_PASSED_CONNECTIONS, passed_connections, 0);
  }
  #[inline]
  pub fn add_dropped_connections(&mut self, dropped_connections: u32) {
    self.fbb_.push_slot::<u32>(TelemetryReport::VT_DROPPED_CONNECTIONS, dropped_connections, 0);
  }
  #[inline]
  pub fn add_anomaly_flags_count(&mut self, anomaly_flags_count: u32) {
    self.fbb_.push_slot::<u32>(TelemetryReport::VT_ANOMALY_FLAGS_COUNT, anomaly_flags_count, 0);
  }
  #[inline]
  pub fn add_heuristic_flags_count(&mut self, heuristic_flags_count: u32) {
    self.fbb_.push_slot::<u32>(TelemetryReport::VT_HEURISTIC_FLAGS_COUNT, heuristic_flags_count, 0);
  }
  #[inline]
  pub fn add_infra_alert_count(&mut self, infra_alert_count: u32) {
    self.fbb_.push_slot::<u32>(TelemetryReport::VT_INFRA_ALERT_COUNT, infra_alert_count, 0);
  }
  #[inline]
  pub fn add_port_entropy_score(&mut self, port_entropy_score: f32) {
    self.fbb_.push_slot::<f32>(TelemetryReport::VT_PORT_ENTROPY_SCORE, port_entropy_score, 0.0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> TelemetryReportBuilder<'a, 'b> {
    let start = _fbb.start_table();
    TelemetryReportBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<TelemetryReport<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for TelemetryReport<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("TelemetryReport");
      ds.field("network_id", &self.network_id());
      ds.field("mac", &self.mac());
      ds.field("bytes_in", &self.bytes_in());
      ds.field("bytes_out", &self.bytes_out());
      ds.field("unique_internal_ips", &self.unique_internal_ips());
      ds.field("unique_external_ips", &self.unique_external_ips());
      ds.field("total_connections", &self.total_connections());
      ds.field("passed_connections", &self.passed_connections());
      ds.field("dropped_connections", &self.dropped_connections());
      ds.field("anomaly_flags_count", &self.anomaly_flags_count());
      ds.field("heuristic_flags_count", &self.heuristic_flags_count());
      ds.field("infra_alert_count", &self.infra_alert_count());
      ds.field("port_entropy_score", &self.port_entropy_score());
      ds.finish()
  }
}
pub enum RouterMessageOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct RouterMessage<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for RouterMessage<'a> {
  type Inner = RouterMessage<'a>;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table { buf, loc } }
  }
}

impl<'a> RouterMessage<'a> {
  pub const VT_PAYLOAD_TYPE: flatbuffers::VOffsetT = 4;
  pub const VT_PAYLOAD: flatbuffers::VOffsetT = 6;

  #[inline]
  pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    RouterMessage { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args RouterMessageArgs
  ) -> flatbuffers::WIPOffset<RouterMessage<'bldr>> {
    let mut builder = RouterMessageBuilder::new(_fbb);
    if let Some(x) = args.payload { builder.add_payload(x); }
    builder.add_payload_type(args.payload_type);
    builder.finish()
  }


  #[inline]
  pub fn payload_type(&self) -> IncomingPayload {
    self._tab.get::<IncomingPayload>(RouterMessage::VT_PAYLOAD_TYPE, Some(IncomingPayload::NONE)).unwrap()
  }
  #[inline]
  pub fn payload(&self) -> Option<flatbuffers::Table<'a>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Table<'a>>>(RouterMessage::VT_PAYLOAD, None)
  }
  #[inline]
  #[allow(non_snake_case)]
  pub fn payload_as_register_request(&self) -> Option<RegisterRequest<'a>> {
    if self.payload_type() == IncomingPayload::RegisterRequest {
      self.payload().map(RegisterRequest::init_from_table)
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn payload_as_change_state_request(&self) -> Option<ChangeStateRequest<'a>> {
    if self.payload_type() == IncomingPayload::ChangeStateRequest {
      self.payload().map(ChangeStateRequest::init_from_table)
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn payload_as_telemetry_report(&self) -> Option<TelemetryReport<'a>> {
    if self.payload_type() == IncomingPayload::TelemetryReport {
      self.payload().map(TelemetryReport::init_from_table)
    } else {
      None
    }
  }

}

impl flatbuffers::Verifiable for RouterMessage<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_union::<IncomingPayload, _>("payload_type", Self::VT_PAYLOAD_TYPE, "payload", Self::VT_PAYLOAD, false, |key, v, pos| {
        match key {
          IncomingPayload::RegisterRequest => v.verify_union_variant::<flatbuffers::ForwardsUOffset<RegisterRequest>>("IncomingPayload::RegisterRequest", pos),
          IncomingPayload::ChangeStateRequest => v.verify_union_variant::<flatbuffers::ForwardsUOffset<ChangeStateRequest>>("IncomingPayload::ChangeStateRequest", pos),
          IncomingPayload::TelemetryReport => v.verify_union_variant::<flatbuffers::ForwardsUOffset<TelemetryReport>>("IncomingPayload::TelemetryReport", pos),
          _ => Ok(()),
        }
     })?
     .finish();
    Ok(())
  }
}
pub struct RouterMessageArgs {
    pub payload_type: IncomingPayload,
    pub payload: Option<flatbuffers::WIPOffset<flatbuffers::UnionWIPOffset>>,
}
impl<'a> Default for RouterMessageArgs {
  #[inline]
  fn default() -> Self {
    RouterMessageArgs {
      payload_type: IncomingPayload::NONE,
      payload: None,
    }
  }
}

pub struct RouterMessageBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> RouterMessageBuilder<'a, 'b> {
  #[inline]
  pub fn add_payload_type(&mut self, payload_type: IncomingPayload) {
    self.fbb_.push_slot::<IncomingPayload>(RouterMessage::VT_PAYLOAD_TYPE, payload_type, IncomingPayload::NONE);
  }
  #[inline]
  pub fn add_payload(&mut self, payload: flatbuffers::WIPOffset<flatbuffers::UnionWIPOffset>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(RouterMessage::VT_PAYLOAD, payload);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> RouterMessageBuilder<'a, 'b> {
    let start = _fbb.start_table();
    RouterMessageBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<RouterMessage<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for RouterMessage<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("RouterMessage");
      ds.field("payload_type", &self.payload_type());
      match self.payload_type() {
        IncomingPayload::RegisterRequest => {
          if let Some(x) = self.payload_as_register_request() {
            ds.field("payload", &x)
          } else {
            ds.field("payload", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        IncomingPayload::ChangeStateRequest => {
          if let Some(x) = self.payload_as_change_state_request() {
            ds.field("payload", &x)
          } else {
            ds.field("payload", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        IncomingPayload::TelemetryReport => {
          if let Some(x) = self.payload_as_telemetry_report() {
            ds.field("payload", &x)
          } else {
            ds.field("payload", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        _ => {
          let x: Option<()> = None;
          ds.field("payload", &x)
        },
      };
      ds.finish()
  }
}
pub enum RouterResponseOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct RouterResponse<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for RouterResponse<'a> {
  type Inner = RouterResponse<'a>;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table { buf, loc } }
  }
}

impl<'a> RouterResponse<'a> {
  pub const VT_STATUS: flatbuffers::VOffsetT = 4;
  pub const VT_MAC: flatbuffers::VOffsetT = 6;

  #[inline]
  pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    RouterResponse { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args RouterResponseArgs<'args>
  ) -> flatbuffers::WIPOffset<RouterResponse<'bldr>> {
    let mut builder = RouterResponseBuilder::new(_fbb);
    if let Some(x) = args.mac { builder.add_mac(x); }
    if let Some(x) = args.status { builder.add_status(x); }
    builder.finish()
  }


  #[inline]
  pub fn status(&self) -> Option<&'a str> {
    self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(RouterResponse::VT_STATUS, None)
  }
  #[inline]
  pub fn mac(&self) -> Option<&'a str> {
    self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(RouterResponse::VT_MAC, None)
  }
}

impl flatbuffers::Verifiable for RouterResponse<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("status", Self::VT_STATUS, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("mac", Self::VT_MAC, false)?
     .finish();
    Ok(())
  }
}
pub struct RouterResponseArgs<'a> {
    pub status: Option<flatbuffers::WIPOffset<&'a str>>,
    pub mac: Option<flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for RouterResponseArgs<'a> {
  #[inline]
  fn default() -> Self {
    RouterResponseArgs {
      status: None,
      mac: None,
    }
  }
}

pub struct RouterResponseBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> RouterResponseBuilder<'a, 'b> {
  #[inline]
  pub fn add_status(&mut self, status: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(RouterResponse::VT_STATUS, status);
  }
  #[inline]
  pub fn add_mac(&mut self, mac: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(RouterResponse::VT_MAC, mac);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> RouterResponseBuilder<'a, 'b> {
    let start = _fbb.start_table();
    RouterResponseBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<RouterResponse<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for RouterResponse<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("RouterResponse");
      ds.field("status", &self.status());
      ds.field("mac", &self.mac());
      ds.finish()
  }
}
#[inline]
#[deprecated(since="2.0.0", note="Deprecated in favor of `root_as...` methods.")]
pub fn get_root_as_router_message<'a>(buf: &'a [u8]) -> RouterMessage<'a> {
  unsafe { flatbuffers::root_unchecked::<RouterMessage<'a>>(buf) }
}

#[inline]
#[deprecated(since="2.0.0", note="Deprecated in favor of `root_as...` methods.")]
pub fn get_size_prefixed_root_as_router_message<'a>(buf: &'a [u8]) -> RouterMessage<'a> {
  unsafe { flatbuffers::size_prefixed_root_unchecked::<RouterMessage<'a>>(buf) }
}

#[inline]
/// Verifies that a buffer of bytes contains a `RouterMessage`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_router_message_unchecked`.
pub fn root_as_router_message(buf: &[u8]) -> Result<RouterMessage, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<RouterMessage>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `RouterMessage` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_router_message_unchecked`.
pub fn size_prefixed_root_as_router_message(buf: &[u8]) -> Result<RouterMessage, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<RouterMessage>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `RouterMessage` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_router_message_unchecked`.
pub fn root_as_router_message_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<RouterMessage<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<RouterMessage<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `RouterMessage` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_router_message_unchecked`.
pub fn size_prefixed_root_as_router_message_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<RouterMessage<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<RouterMessage<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a RouterMessage and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `RouterMessage`.
pub unsafe fn root_as_router_message_unchecked(buf: &[u8]) -> RouterMessage {
  flatbuffers::root_unchecked::<RouterMessage>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed RouterMessage and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `RouterMessage`.
pub unsafe fn size_prefixed_root_as_router_message_unchecked(buf: &[u8]) -> RouterMessage {
  flatbuffers::size_prefixed_root_unchecked::<RouterMessage>(buf)
}
#[inline]
pub fn finish_router_message_buffer<'a, 'b>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    root: flatbuffers::WIPOffset<RouterMessage<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_router_message_buffer<'a, 'b>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>, root: flatbuffers::WIPOffset<RouterMessage<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
